#ifndef INCLUDED_ETVR_SYSTEM_HPP
#define INCLUDED_ETVR_SYSTEM_HPP

#if CONFIG_CAMERA_MODULE_ESPS3WROVER
#define ETVR_EYE_TRACKER_USB_API
#else
#define ETVR_EYE_TRACKER_WEB_API
#endif

#endif  // INCLUDED_ETVR_SYSTEM_HPP
